language: ruby
rvm:
  - 2.3.0
env:
  - DB=postgres
services:
  - postgresql
before_script:
  - psql -c 'create database johari_window_api_test;' -U postgres
script:
  - bundle exec rspec --tag ~type:special
cache: bundler
notifications:
  email:
    on_success: never
    on_failure: always
